# https://taskfile.dev

version: "3"

vars:
   DOWNLOAD_SYNCTHING_VERSION: "v2.0.3"

tasks:
   download-syncthing:
      desc: "Download and extract syncthing"
      cmds:
         - powershell -ExecutionPolicy Bypass -File scripts/download-syncthing.ps1 -Version "{{.DOWNLOAD_SYNCTHING_VERSION}}"
      platforms: [windows]
      run: once
   upgrade-syncthing:
      desc: "Upgrade local syncthing binary"
      deps:
         - download-syncthing
      cmds:
         - powershell -ExecutionPolicy Bypass -File scripts/upgrade-syncthing.ps1
      platforms: [windows]
      run: once
   build:
      desc: "Build SyncTrayzor"
      deps:
         - upgrade-syncthing
      cmds:
         - powershell -ExecutionPolicy Bypass -File scripts/build-dist.ps1 -Variant "{{.variant}}"
      requires:
         vars:
            - variant
      platforms: [windows]
   build-portable:
      desc: "Build SyncTrayzor in portable configuration"
      cmds:
         - task: build
           vars:
              variant: "Portable"
         - powershell -ExecutionPolicy Bypass -File scripts/build-portable.ps1
      platforms: [windows]
   build-installer:
      desc: "Build SyncTrayzor with installer"
      cmds:
         - task: build
           vars:
              variant: "Installed"
         - powershell -ExecutionPolicy Bypass -File scripts/build-inno-setup.ps1
      platforms: [windows]
   build-choco-package:
      desc: "Create Chocolatey package"
      cmds:
         - powershell -ExecutionPolicy Bypass -File scripts/build-choco-package.ps1
      run: once
   sign-release:
      desc: "Sign release files in ./release folder"
      cmds:
         - powershell -ExecutionPolicy Bypass -File scripts/sign-release.ps1
      platforms: [windows]
      run: once
