name: Publish to WinGet
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to publish (e.g., v1.2.3)'
        required: true
        type: string
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Get release info
        id: release_info
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v7
        with:
          script: |
            const tag = '${{ github.event.inputs.release_tag }}';
            const { data: release } = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag
            });
            return release;
          result-encoding: string
      
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: GermanCoding.SyncTrayzor
          installers-regex: '-x64\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
          version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag || '' }}